--test
DELETE FROM ADRESSE;
DELETE FROM BESTELLPOSTEN;
DELETE FROM BESTELLUNG_LIEFERUNG;
DELETE FROM KUNDE_HOBBY;
DELETE FROM LIEFERUNG;
DELETE FROM GESCHLECHT;
DELETE FROM FAMILIENSTAND;
DELETE FROM TRANSPORT_ART;
DELETE FROM HOBBY;
DELETE FROM WARTUNGSVERTRAG;
DELETE FROM BESTELLUNG;
DELETE FROM ARTIKEL;
DELETE FROM KUNDE;